name: Auto Merge Master to Main

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge master into main
        run: |
          git merge origin/master --no-edit

      - name: Push changes
        run: |
          git push origin main
